### ISSUE TITLE
Codeblocks in Live Docs are illegible

### ISSUE THREAD

**Issue by DhruvaSambrani** [Pocket-titan/DarkMode#4]
I'd love to fix this myself, but I don't know the CSS structure of Pluto, and I'm not free right now to do it. 
I presume its only about 3 lines of code change, and think that it'd be a great first issue 😃

**Comment by DhruvaSambrani** [comment]
As a related issue, the arrow on LiveDocs is invisible

**Comment by danvinci** [comment]
I'm using Stylebot on Firefox with the following settings:

```
thead tr th {
  background-color: #18191B;
  color: #E6E6E6;
}

tbody tr th {
  background-color: #18191B;
}

pluto-helpbox div div pre {
  background-color: #292D3E;
  border-color: #1A1A1A;
```

Colors were picked from existing ones, my issue was mostly about tables (first two) but the last one addresses the docs.
It may be necessary to refresh and/or to re-run the cell that enables dark mode, but for now, this is doing the trick.

**Comment by Pocket-titan** [comment]
The code blocks in the Livedocs should now correctly respect your custom codemirror theme!
